# name of your github action
name: Lint and Unit Test

# this will help you specify where to run
on:
  pull_request:
    branches: [ main, develop, ci-cd ]

# this is where the magic happens, each job happens in parallel btw
jobs:

  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint
      - run: npm test
